# NumPy element-wise multiplication tests

In [2]:
import numpy as np

## Element wise multiplication

### A(2, 2) 
### b(2,)
<div class="alert alert-block alert-success">
    <b>Broadcasting OK</b>
</div>
Nota: il prodotto scalare avrebbe ritornato un vettore (2, 1)

In [3]:
A = np.array([[1,2], [3,4]])
b = np.array([2, 2])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

c = A*b
print(c)
print(f'Shape c: {c.shape}')

Shape A: (2, 2)
Shape b: (2,)
[[2 4]
 [6 8]]
Shape c: (2, 2)


### A(2, 2)
### b(1, 2)
<div class="alert alert-block alert-success">
    <b>Broadcasting OK</b> Stesso risultato di sopra <br>
    Nota: in questo caso il Broadcasting è come se avesse replicato il vettore riga <b>b</b> su una seconda riga
</div>

In [4]:
A = np.array([[1,2], [3,4]])
b = np.array([[2, 2]])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

c = A*b
print(c)
print(f'Shape c: {c.shape}')

Shape A: (2, 2)
Shape b: (1, 2)
[[2 4]
 [6 8]]
Shape c: (2, 2)


### A(2, 2)
### b(2, 1)
<div class="alert alert-block alert-success">
    <b>Broadcasting OK</b> Stesso risultato di sopra <br>
    Nota: in questo caso il Broadcasting è come se avesse replicato il vettore riga <b>b</b> su una seconda colonna
</div>

In [5]:
A = np.array([[1,2], [3,4]])
b = np.array([[2],[2]])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

c = A*b
print(c)
print(f'Shape c: {c.shape}')

Shape A: (2, 2)
Shape b: (2, 1)
[[2 4]
 [6 8]]
Shape c: (2, 2)


### A(3, 2)
### b(2,)
<div class="alert alert-block alert-success">
    <b>Broadcasting OK</b>
</div>

In [6]:
A = np.array([[1,2], [3,4], [5, 6]])
b = np.array([2, 2])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

C = A*b
print(C)
print(f'Shape c: {C.shape}')

Shape A: (3, 2)
Shape b: (2,)
[[ 2  4]
 [ 6  8]
 [10 12]]
Shape c: (3, 2)


### A(2, 3)
### B(2,)
<div class="alert alert-block alert-danger">
    <b>Broadcasting FALLISCE</b> <br> Non è possibile espandere (replicare) <b>b</b> su alcuna dimensione per ottenere esattamente lo shape di <b>A</b>
</div>

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 1])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

c = A*b
print(c)
print(f'Shape c: {c.shape}')

Shape A: (2, 3)
Shape b: (2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### A(3, 3)
### B(3, 3)
**Non occorre Broadcasting**

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Shape A: {A.shape}')
print(f'Shape B: {B.shape}')

C = A*B
print(C)
print(f'Shape C: {C.shape}')

Shape A: (2, 3)
Shape B: (2, 3)
[[ 1  4  9]
 [16 25 36]]
Shape C: (2, 3)


### A(2, 3)
### B(3, 2)
<div class="alert alert-block alert-danger">
    <b>Broadcasting FALLISCE</b> <br> Non è possibile espandere (replicare) <b>b</b> su alcuna dimensione per ottenere esattamente lo shape di <b>A</b>
</div>

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

print(f'Shape A: {A.shape}')
print(f'Shape B: {B.shape}')

C = A*B
print(C)
print(f'Shape C: {C.shape}')

Shape A: (2, 3)
Shape B: (3, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### Test caso complesso (4 dimensioni)
Obbiettivo: moltiplicare l'intera matrice **P** per ogni valore di **K**.
<br>
I due test successivi devono verificare se la strategia di calcolo presentata fornisce il risultato sperato

In [10]:
P = np.ones((2, 362, 200))
k = np.arange(257)

print(f'{k}')

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### Test 1
<div class="alert alert-block alert-success">
    <b>Il test FUNZIONA</b> <br>Broadcasting di <b>K</b> aggiungendo dimensione in fondo a <b>P</b> <br>
Obbiettivo: per ogni indice del vettore <b>k</b>, devo ottenere una matrice tridimensionale che replica su tutti i suoi elementi il valore <b>k[i]</b>
</div>

In [37]:
TEST_1 = P[..., np.newaxis]*k
print(f'Shape TEST_1: {TEST_1.shape}')
print(f'Next array should contain all 0')
print(TEST_1[..., 0])
print(f'Next array should contain all 1')
print(TEST_1[..., 1])

print(f'Next array should contain all 5')
print(TEST_1[..., 5])


Shape TEST_1: (2, 362, 200, 257)
Next array should contain all 0
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
Next array should contain all 1
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
Next array should contain all 5
[[[5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]
  ...
  [5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]]

 [[5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]

#### Test 2
<div class="alert alert-block alert-success">
    <b>Il test FUNZIONA</b> <br>Broadcasting di <b>K</b> aggiungendo una nuova dimensione più esterna a <b>P</b>
Obbiettivo: per ogni indice del vettore <b>k</b>, devo ottenere una matrice tridimensionale che replica su tutti i suoi elementi il valore <b>k[i]</b>
</div>

In [38]:
TEST_2 = P[np. newaxis, ...]*k[:, np.newaxis, np.newaxis, np.newaxis]
print(f'Shape TEST_1: {TEST_2.shape}')
print(f'Next array should contain all 0')
print(TEST_2[0, ...])
print(f'Next array should contain all 1')
print(TEST_2[1, ...])

print(f'Next array should contain all 5')
print(TEST_2[5, ...])



Shape TEST_1: (257, 2, 362, 200)
Next array should contain all 0
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
Next array should contain all 1
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
Next array should contain all 5
[[[5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]
  ...
  [5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]]

 [[5. 5. 5. ... 5. 5. 5.]
  [5. 5. 5. ... 5. 5. 5.]

### Test caso complesso (5 dimensioni)
Obbiettivo: moltiplicare l'intera matrice P per ogni valore di K.
<br>
I due test successivi devono verificare se la strategia di calcolo presentata fornisce il risultato sperato

In [49]:
P = np.ones((2, 362, 200))
k = np.stack([np.arange(256), 10*np.arange(256)], axis=1)

print(f'Shape k: {k.shape}')
print(f'{k}')


Shape k: (256, 2)
[[   0    0]
 [   1   10]
 [   2   20]
 [   3   30]
 [   4   40]
 [   5   50]
 [   6   60]
 [   7   70]
 [   8   80]
 [   9   90]
 [  10  100]
 [  11  110]
 [  12  120]
 [  13  130]
 [  14  140]
 [  15  150]
 [  16  160]
 [  17  170]
 [  18  180]
 [  19  190]
 [  20  200]
 [  21  210]
 [  22  220]
 [  23  230]
 [  24  240]
 [  25  250]
 [  26  260]
 [  27  270]
 [  28  280]
 [  29  290]
 [  30  300]
 [  31  310]
 [  32  320]
 [  33  330]
 [  34  340]
 [  35  350]
 [  36  360]
 [  37  370]
 [  38  380]
 [  39  390]
 [  40  400]
 [  41  410]
 [  42  420]
 [  43  430]
 [  44  440]
 [  45  450]
 [  46  460]
 [  47  470]
 [  48  480]
 [  49  490]
 [  50  500]
 [  51  510]
 [  52  520]
 [  53  530]
 [  54  540]
 [  55  550]
 [  56  560]
 [  57  570]
 [  58  580]
 [  59  590]
 [  60  600]
 [  61  610]
 [  62  620]
 [  63  630]
 [  64  640]
 [  65  650]
 [  66  660]
 [  67  670]
 [  68  680]
 [  69  690]
 [  70  700]
 [  71  710]
 [  72  720]
 [  73  730]
 [  74  740]
 [  75 

#### Test 1
<div class="alert alert-block alert-success">
    <b>Il test FUNZIONA</b> <br>Broadcasting di <b>K</b> aggiungendo dimensione in fondo a <b>P</b>
Obbiettivo: per <b>j=0</b> (prima colonna di <b>k</b>), il test deve restituire gli stessi risultati di sopra. Per <b>j=1</b> (seconda colonna di <b>k</b>), il test deve restituire gli stessi valori di <b>j=0</b> moltiplicati per 10
</div>

In [52]:
TEST_1 = P[..., np.newaxis, np.newaxis]*k
print(f'Shape TEST_1: {TEST_1.shape}')
print(f'Next array should contain all 0')
print(TEST_1[..., 0, 0])
print(f'Next array should contain all 0')
print(TEST_1[..., 0, 1])

print(f'Next array should contain all 1')
print(TEST_1[..., 1, 0])
print(f'Next array should contain all 10')
print(TEST_1[..., 1, 1])

print(f'Next array should contain all 5')
print(TEST_1[..., 5, 0])
print(f'Next array should contain all 50')
print(TEST_1[..., 5, 1])


Shape TEST_1: (2, 362, 200, 256, 2)
Next array should contain all 0
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
Next array should contain all 0
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
Next array should contain all 1
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 