# Indexing tutorial

In [24]:
import numpy as np

In [28]:
a = np.array([1,2,3,4,5])
B = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
C = np.stack((B, -1*B), axis=0)
print(C.shape)

(2, 3, 5)


## Basic indexing


In [26]:
print(a[0])
print(B[0,1])
print(C[1,1,1])

1
2
-7


## Basic slicing
**[start:stop:step]** <font color=red>stop is not included in the range</font>

All arrays generated by basic slicing are always views of the original array.


In [29]:
a_sliced=a[0:4:1]
print(a_sliced)

a2_sliced = a[2:] # all elements until last one
print(a2_sliced)

[1 2 3 4]
[3 4 5]


### Reverse slicing

Note the index start and stop need to follow the step direction

In [30]:
a3_sliced = a[0:4:-1]
print(a3_sliced) # empty view
a4_sliced = a[4:0:-1] # reversed a_sliced
print(a4_sliced)

[]
[5 4 3 2]


In [31]:
B_sliced= B[:, 1:3]
print(B_sliced)

[[ 2  3]
 [ 7  8]
 [12 13]]


In [32]:
C_sliced = C[1, ...] # ellipsis: means 'all elements for all subsequent dimensions'
print(C_sliced)

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]
 [-11 -12 -13 -14 -15]]


If a number of dimensions less than array.ndim is given, all lacking dimensions are intended as :

In [35]:
C2_sliced = C[1:] # first dimension is given, dimensions 2 and 3 are intended as : -> C[1,:,:]
print(C2_sliced)
print(f'NOTE: C_sliced ndim: {C_sliced.ndim}\nC2_sliced ndim: {C2_sliced.ndim}')

[[[ -1  -2  -3  -4  -5]
  [ -6  -7  -8  -9 -10]
  [-11 -12 -13 -14 -15]]]
NOTE: C_sliced ndim: 2
C2_sliced ndim: 3


### Slicing view dimensionality expansion

In [37]:
B_sliced_expanded = B[1, np.newaxis, 2:4] # added an empty dimension before getting elements from 2nd dimension of B
print(B_sliced_expanded) # the result is a new couple of square brackets [] outside from [8 9]

[[8 9]]


In [38]:
B_sliced_expanded = B[1, 2:4, np.newaxis] # added an empty dimension before getting elements from 2nd dimension of B
print(B_sliced_expanded) # [8 9] from B is now promoted to row elements, while the new dimension creates the columns

[[8]
 [9]]


## Advanced indexing
<div class="alert alert-block alert-danger">
    <b>Advanced slicing produces copies of the arrays, not views</b>
</div>

In [41]:
D = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

### Using integer arrays as source for specific indexes
Each dimension of a target array can be indexed through numpy arrays that contains integer number.
An array of integer non negative indexes is produced for each dimension of interest. <font color=red>Each position in the index array of each dimension selects a specific element</font>. E.g. all the first elements of the indexes arrays select one first element from the target array. All the second elements of the indexes arrays select one second element from the target array, and so forth. <font color=red>This means the number of elements within index arrays should be the same</font>
The only remaining constraint is that all elements of numpy arrays used for indexing are within 0 and size_of_dimension-1

In [45]:
indexes_for_rows = np.array([0, 2], dtype=np.intp)
indexes_for_columns = np.array([1, 4], dtype=np.intp)

D_copy_subindexed = D[indexes_for_rows, indexes_for_columns] # select elements [0, 1] and [2, 4]
print(D_copy_subindexed)

[ 2 15]


### Boolean array indexing
Basically, a boolean array of the **same size of the target array** is returned, which hosts booleans according to array values that respected a tested condition. This boolean array can then be used within the target array itself to finally extract values of interest. These values are returned in a 1D array.
This is used each time the user is finally interested in extracting **values** from the target array.

In [49]:
boolean_C = C<0 # conditions can be assigned as numpy arrays
print(boolean_C)
C_extracted_values = C[C<0]
print(C_extracted_values) # 1D array

[[[False False False False False]
  [False False False False False]
  [False False False False False]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


### Extracting through 'np.where'
This instruction extracts indexes satisfying the condition expressed as where argument.

<div class="alert alert-block alert-danger">
    <b>'where' returns a number of arrays equal to the target array ndim. Each array contains all indexes of that dimension for which the target array has satisfied the condition</b>
</div>
<div class="alert alert-block alert-danger">
    <b>Each element refers to a specific index position within all returned index arrays. This is the same concept behind advanced indexing using integer arrays</b>
</div>

In [53]:
first_dim_indexes, second_dim_indexes, third_dim_indexes = np.where(C<0)
print(f'first_dim_indexes: {first_dim_indexes}, length {first_dim_indexes.size}') #same length for all index arrays
print(f'second_dim_indexes: {second_dim_indexes}, length {second_dim_indexes.size}') #same length for all index arrays
print(f'third_dim_indexes: {third_dim_indexes}, length {third_dim_indexes.size}') #same length for all index arrays
# extract elements with advanced array indexing
print(C[first_dim_indexes, second_dim_indexes, third_dim_indexes])

first_dim_indexes: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], length 15
second_dim_indexes: [0 0 0 0 0 1 1 1 1 1 2 2 2 2 2], length 15
third_dim_indexes: [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4], length 15
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]
