# NumPy scalar multiplication tests

In [6]:
import numpy as np

## Scalar multiplication
In numpy il prodotto scalare tra **A** e **B** varia a seconda delle dimensioni di **A** e **B**

Poichè non si parla di prodotto elemento per elemento <a style="color:red"> per il prodotto scalare non esiste il concetto di <b>broadcasting</b> </a>

Il prodotto riga colonna è da considerarsi come: 
1. riga=penultima dimensione di **A**
1. colonna=ultima dimensione di **b**

### A(2, 2) 
### b(2,)
<div class="alert alert-block alert-success">
    <b>Prodotto scalare OK</b>
</div>

In [41]:
A = np.array([[1,2], [3,4]])
b = np.array([2, 2])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

c=A@b
print(f'Shape c: {c.shape}')
print(f'c={c}')

Shape A: (2, 2)
Shape b: (2,)
Shape c: (2,)
c=[ 6 14]


### A(2, 2)
### b(1, 2)
<div class="alert alert-block alert-danger">
<b>Prodotto scalare FALLISCE</b> <br> A(2x2) B(1x2) le dimensioni interne non coincidono
</div>

In [40]:
A = np.array([[1,2], [3,4]])
b = np.array([[2, 2]])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')
c=A@b
print(f'Shape c: {c.shape}')
print(f'c={c}')

Shape A: (2, 2)
Shape b: (1, 2)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

### A(2, 2)
### b(2, 1)
<div class="alert alert-block alert-success">
    <b>Prodotto scalare OK</b>
    <br>
    A(2x2) B(2x1) le dimensioni interne sono compatibili
    <br>
    Viene ritornato un vettore colonna
</div>

In [39]:
A = np.array([[1,2], [3,4]])
b = np.array([[2],[2]])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

c = A@b
print(f'Shape c: {c.shape}')
print(f'c={c}')

Shape A: (2, 2)
Shape b: (2, 1)
Shape c: (2, 1)
c=[[ 6]
 [14]]


### A(2, 3)
### B(2,)
<div class="alert alert-block alert-danger">
<b>Prodotto scalare FALLISCE</b> <br> A(2x2) B(2,) le dimensioni interne non coincidono
</div>

In [38]:
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 1])

print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

c = A@b
print(f'Shape c: {c.shape}')
print(f'c={c}')

Shape A: (2, 3)
Shape b: (2,)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### A(2, 3)
### B(3, 2)
<div class="alert alert-block alert-success">
    <b>Prodotto scalare OK</b>
    <br>
    A(2x2) B(2x2) le dimensioni interne sono compatibili
    <br>
    Viene ritornato un vettore (2x2)
</div>

In [37]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

print(f'Shape A: {A.shape}')
print(f'Shape B: {B.shape}')

C = A@B
print(f'Shape C: {C.shape}')
print(f'C={C}')

Shape A: (2, 3)
Shape B: (3, 2)
Shape C: (2, 2)
C=[[22 28]
 [49 64]]


### Test caso complesso 1
#### A(2, 362, 200)
#### b(200,)
Obbiettivo: prodotto scalare tra matrice **A** e vettore **b**.
<br>
Il risultato è una matrice 2x362
<div class="alert alert-block alert-info">
    <b>Nota:</b> Tutti i valori del vettore <b>A</b> risentono del prodotto scalare
</div>

In [47]:
A = np.ones((2, 362, 200))
b = np.ones(200)
print(f'Shape A: {A.shape}')
print(f'Shape b: {b.shape}')

C = A@b
print(f'Shape C: {C.shape}')
print(f'C = {C}')

Shape A: (2, 362, 200)
Shape b: (200,)
Shape C: (2, 362)
C = [[200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.
  2

### Test caso complesso 2
#### A(2, 362, 200)
#### B(200, 400)
Obbiettivo: prodotto scalare tra matrice **A** e vettore **B**.
<br>
Il risultato è una matrice 2x362x400
<div class="alert alert-block alert-info">
    <b>Nota:</b> Tutti i valori del vettore <b>A</b> risentono del prodotto scalare
</div>

In [46]:
A = np.ones((2, 362, 200))
B = np.ones((200, 400))
print(f'Shape A: {A.shape}')
print(f'Shape B: {B.shape}')

C = A@B
print(f'Shape C: {C.shape}')
print(f'C = {C}')

Shape A: (2, 362, 200)
Shape B: (200, 400)
Shape C: (2, 362, 400)
C = [[[200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]
  ...
  [200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]]

 [[200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]
  ...
  [200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]
  [200. 200. 200. ... 200. 200. 200.]]]
